# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets

class record_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(324, 315)
        Dialog.setMinimumSize(QtCore.QSize(324, 315))
        Dialog.setMaximumSize(QtCore.QSize(324, 315))
        self.Titile = QtWidgets.QLabel(Dialog)
        self.Titile.setGeometry(QtCore.QRect(90, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Titile.setFont(font)
        self.Titile.setAlignment(QtCore.Qt.AlignCenter)
        self.Titile.setWordWrap(False)
        self.Titile.setObjectName("Titile")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 80, 204, 183))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.SecondgradeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.SecondgradeLabel.setMinimumSize(QtCore.QSize(100, 50))
        self.SecondgradeLabel.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SecondgradeLabel.setFont(font)
        self.SecondgradeLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.SecondgradeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SecondgradeLabel.setText("")
        self.SecondgradeLabel.setObjectName("SecondgradeLabel")
        self.gridLayout.addWidget(self.SecondgradeLabel, 1, 1, 1, 1)
        self.SecondLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.SecondLabel.setMinimumSize(QtCore.QSize(100, 50))
        self.SecondLabel.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SecondLabel.setFont(font)
        self.SecondLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.SecondLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SecondLabel.setObjectName("SecondLabel")
        self.gridLayout.addWidget(self.SecondLabel, 1, 0, 1, 1)
        self.FirstgradeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.FirstgradeLabel.setMinimumSize(QtCore.QSize(100, 50))
        self.FirstgradeLabel.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FirstgradeLabel.setFont(font)
        self.FirstgradeLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.FirstgradeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FirstgradeLabel.setText("")
        self.FirstgradeLabel.setObjectName("FirstgradeLabel")
        self.gridLayout.addWidget(self.FirstgradeLabel, 0, 1, 1, 1)
        self.ThirdLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ThirdLabel.setMinimumSize(QtCore.QSize(100, 50))
        self.ThirdLabel.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ThirdLabel.setFont(font)
        self.ThirdLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.ThirdLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ThirdLabel.setObjectName("ThirdLabel")
        self.gridLayout.addWidget(self.ThirdLabel, 2, 0, 1, 1)
        self.ThirdgradeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ThirdgradeLabel.setMinimumSize(QtCore.QSize(100, 50))
        self.ThirdgradeLabel.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ThirdgradeLabel.setFont(font)
        self.ThirdgradeLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.ThirdgradeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ThirdgradeLabel.setText("")
        self.ThirdgradeLabel.setObjectName("ThirdgradeLabel")
        self.gridLayout.addWidget(self.ThirdgradeLabel, 2, 1, 1, 1)
        self.FirstLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.FirstLabel.setMinimumSize(QtCore.QSize(100, 50))
        self.FirstLabel.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FirstLabel.setFont(font)
        self.FirstLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.FirstLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FirstLabel.setObjectName("FirstLabel")
        self.gridLayout.addWidget(self.FirstLabel, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.ConfirmButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.verticalLayout_2.addWidget(self.ConfirmButton)

        self.FirstgradeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SecondgradeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ThirdgradeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FirstLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SecondLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ThirdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Titile.setAlignment(QtCore.Qt.AlignCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "最佳纪录"))
        self.Titile.setText(_translate("Dialog", "历史最佳纪录"))
        self.SecondLabel.setText(_translate("Dialog", "第二名"))
        self.ThirdLabel.setText(_translate("Dialog", "第三名"))
        self.FirstLabel.setText(_translate("Dialog", "第一名"))
        self.ConfirmButton.setText(_translate("Dialog", "OK"))

