# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(1131, 842)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(8)
        Dialog.setFont(font)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setWindowTitle("")
        Dialog.setWindowOpacity(1.0)
        Dialog.setToolTip("")
        Dialog.setStatusTip("")
        Dialog.setWhatsThis("")
        Dialog.setStyleSheet("")
        Dialog.setWindowFilePath("")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1161, 841))
        self.widget.setObjectName("widget")
        self.barra = QtWidgets.QWidget(self.widget)
        self.barra.setGeometry(QtCore.QRect(0, 0, 1131, 71))
        self.barra.setStyleSheet("")
        self.barra.setObjectName("barra")
        self.label = QtWidgets.QLabel(self.barra)
        self.label.setGeometry(QtCore.QRect(30, 10, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ls_icon = QtWidgets.QLabel(self.barra)
        self.ls_icon.setGeometry(QtCore.QRect(810, 0, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.ls_icon.setFont(font)
        self.ls_icon.setStyleSheet("color:#0d111c;")
        self.ls_icon.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.ls_icon.setObjectName("ls_icon")
        self.label_3 = QtWidgets.QLabel(self.barra)
        self.label_3.setGeometry(QtCore.QRect(600, 0, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:black;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.bs_icon = QtWidgets.QLabel(self.barra)
        self.bs_icon.setGeometry(QtCore.QRect(890, 0, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.bs_icon.setFont(font)
        self.bs_icon.setStyleSheet("color:#0d111c;")
        self.bs_icon.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bs_icon.setObjectName("bs_icon")
        self.lb_exit = QtWidgets.QPushButton(self.barra)
        self.lb_exit.setGeometry(QtCore.QRect(1049, -1, 81, 73))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.lb_exit.setFont(font)
        self.lb_exit.setFlat(True)
        self.lb_exit.setObjectName("lb_exit")
        self.bt_store = QtWidgets.QPushButton(self.barra)
        self.bt_store.setGeometry(QtCore.QRect(970, -1, 81, 73))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        self.bt_store.setFont(font)
        self.bt_store.setFlat(True)
        self.bt_store.setObjectName("bt_store")
        self.ls_freecoins = QtWidgets.QPushButton(self.barra)
        self.ls_freecoins.setGeometry(QtCore.QRect(730, 0, 81, 73))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.ls_freecoins.setFont(font)
        self.ls_freecoins.setFlat(True)
        self.ls_freecoins.setObjectName("ls_freecoins")
        self.bt_play = QtWidgets.QPushButton(self.widget)
        self.bt_play.setGeometry(QtCore.QRect(980, 700, 151, 141))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.bt_play.setFont(font)
        self.bt_play.setStyleSheet("background-color:white;")
        self.bt_play.setFlat(True)
        self.bt_play.setObjectName("bt_play")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(0, 69, 1130, 3))
        self.line.setStyleSheet("\n"
"color: rgb(200, 200, 200);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.bt_back = QtWidgets.QPushButton(self.widget)
        self.bt_back.setGeometry(QtCore.QRect(830, 700, 151, 141))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.bt_back.setFont(font)
        self.bt_back.setStyleSheet("background-color:white;")
        self.bt_back.setFlat(True)
        self.bt_back.setObjectName("bt_back")
        self.bt_nav = QtWidgets.QPushButton(self.widget)
        self.bt_nav.setGeometry(QtCore.QRect(680, 700, 151, 141))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.bt_nav.setFont(font)
        self.bt_nav.setStyleSheet("background-color:white;")
        self.bt_nav.setFlat(True)
        self.bt_nav.setObjectName("bt_nav")
        self.bt_powerup = QtWidgets.QPushButton(self.widget)
        self.bt_powerup.setGeometry(QtCore.QRect(530, 700, 151, 141))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.bt_powerup.setFont(font)
        self.bt_powerup.setStyleSheet("background-color:white;")
        self.bt_powerup.setFlat(True)
        self.bt_powerup.setObjectName("bt_powerup")
        self.nav_baixo = QtWidgets.QPushButton(self.widget)
        self.nav_baixo.setGeometry(QtCore.QRect(0, 700, 150, 141))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nav_baixo.setFont(font)
        self.nav_baixo.setStyleSheet("background-color:white;")
        self.nav_baixo.setFlat(True)
        self.nav_baixo.setObjectName("nav_baixo")
        self.nivelescolhido = QtWidgets.QPushButton(self.widget)
        self.nivelescolhido.setGeometry(QtCore.QRect(150, 700, 150, 141))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nivelescolhido.setFont(font)
        self.nivelescolhido.setStyleSheet("background-color:white;")
        self.nivelescolhido.setFlat(True)
        self.nivelescolhido.setObjectName("nivelescolhido")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Dialog", "SpaceShipPY"))
        self.ls_icon.setText(_translate("Dialog", "1000"))
        self.label_3.setText(_translate("Dialog", "1000"))
        self.bs_icon.setText(_translate("Dialog", "1000"))
        self.lb_exit.setText(_translate("Dialog", "Sair"))
        self.bt_store.setText(_translate("Dialog", "Loja"))
        self.ls_freecoins.setText(_translate("Dialog", "Coins Gratis"))
        self.bt_play.setText(_translate("Dialog", "Começar"))
        self.bt_back.setText(_translate("Dialog", "Anterior"))
        self.bt_nav.setText(_translate("Dialog", "Naves"))
        self.bt_powerup.setText(_translate("Dialog", "PowerUps"))
        self.nav_baixo.setText(_translate("Dialog", "Nav Escolhida"))
        self.nivelescolhido.setText(_translate("Dialog", "Nivel Escolhido"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

