# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cart.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 320)
        Dialog.setMinimumSize(QtCore.QSize(480, 320))
        Dialog.setMaximumSize(QtCore.QSize(480, 320))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.audio_request = QtWidgets.QPushButton(Dialog)
        self.audio_request.setGeometry(QtCore.QRect(220, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(39)
        self.audio_request.setFont(font)
        self.audio_request.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.audio_request.setObjectName("audio_request")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.user_list = QtWidgets.QListWidget(Dialog)
        self.user_list.setGeometry(QtCore.QRect(330, 60, 131, 192))
        self.user_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.user_list.setObjectName("user_list")
        self.user_cart = QtWidgets.QListWidget(Dialog)
        self.user_cart.setGeometry(QtCore.QRect(160, 60, 151, 192))
        self.user_cart.setObjectName("user_cart")
        self.exit_from_account = QtWidgets.QPushButton(Dialog)
        self.exit_from_account.setGeometry(QtCore.QRect(10, 210, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.exit_from_account.setFont(font)
        self.exit_from_account.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_from_account.setObjectName("exit_from_account")
        self.call_a_shopman = QtWidgets.QPushButton(Dialog)
        self.call_a_shopman.setGeometry(QtCore.QRect(10, 260, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.call_a_shopman.setFont(font)
        self.call_a_shopman.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.call_a_shopman.setObjectName("call_a_shopman")
        self.product_cost = QtWidgets.QPushButton(Dialog)
        self.product_cost.setGeometry(QtCore.QRect(10, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.product_cost.setFont(font)
        self.product_cost.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.product_cost.setObjectName("product_cost")
        self.add_to_cart_2 = QtWidgets.QPushButton(Dialog)
        self.add_to_cart_2.setGeometry(QtCore.QRect(10, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.add_to_cart_2.setFont(font)
        self.add_to_cart_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_to_cart_2.setObjectName("add_to_cart_2")
        self.add_to_cart = QtWidgets.QPushButton(Dialog)
        self.add_to_cart.setGeometry(QtCore.QRect(10, 60, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.add_to_cart.setFont(font)
        self.add_to_cart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_to_cart.setObjectName("add_to_cart")
        self.create_list = QtWidgets.QPushButton(Dialog)
        self.create_list.setGeometry(QtCore.QRect(340, 20, 111, 27))
        self.create_list.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_list.setObjectName("create_list")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(330, 260, 151, 41))
        self.label_2.setMaximumSize(150, 41)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Покупки"))
        self.audio_request.setText(_translate("Dialog", "🎙"))
        self.label.setText(_translate("Dialog", "Корзина"))
        self.exit_from_account.setText(_translate("Dialog", "Выйти из аккаунта"))
        self.call_a_shopman.setText(_translate("Dialog", "Позвать консультанта"))
        self.product_cost.setText(_translate("Dialog", "Узнать цену продукта"))
        self.add_to_cart_2.setText(_translate("Dialog", "Убрать продукт из корзины"))
        self.add_to_cart.setText(_translate("Dialog", "Добавить продукт в корзину"))
        self.create_list.setText(_translate("Dialog", "Изменить список"))
        self.label_2.setText(_translate("Dialog", "Итого: 0₽"))

