import sys

import PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QByteArray

from data_modul import JsonConnector, Chest, SoundThread
from character_modul import Postac


class UiAfterGame(object):
    core = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.chest_timer = None

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.centralwidget.setObjectName("centralwidget")

        self.make_background()
        self.make_exit_btn()
        self.make_start_btn()
        self.make_menu_btn()
        self.make_menu_title()
        self.make_highscore_label()
        self.make_score_label()
        self.make_info_label()
        self.make_coin_label()
        self.make_chest_btn()
        self.make_chest_image()
        self.make_chest_label()

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))
        self.play_btn.setText(_translate("MainWindow", "Try Again"))
        self.menu_title.setText(_translate("MainWindow", "You die"))
        self.chest_btn.setText(_translate("MainWindow", "Open Chest"))
        self.menu_btn.setText(_translate("MainWindow", "Menu"))
        self.load_highscore(_translate)

    def load_highscore(self, _translate):
        high = JsonConnector.get_from_config("highscore")
        self.menu_highscore.setText(_translate("MainWindow", "Highscore: " + str(high)))
        self.score.setText(_translate("MainWindow", "Score: " + str(Postac.score)))
        self.coin_label.setText(_translate("MainWindow", "Coins: " + str(JsonConnector.get_from_config("coins"))))
        if Postac.score > high:
            self.menu_info.setText(_translate("MainWindow", "New Highscore !!!"))
        elif Postac.score > 15000:
            self.menu_info.setText(_translate("MainWindow", "You are magnificent !!!"))
        elif Postac.score > 10000:
            self.menu_info.setText(_translate("MainWindow", "Good Job !!"))
        elif Postac.score > 5000:
            self.menu_info.setText(_translate("MainWindow", "Nice !"))

    def make_highscore_label(self):
        self.menu_highscore = QtWidgets.QLabel(self.centralwidget)
        self.menu_highscore.setGeometry(QtCore.QRect(60, 280, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.menu_highscore.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menu_highscore.setFont(font)
        self.menu_highscore.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_highscore.setObjectName("menu_highscore")

    def make_score_label(self):
        self.score = QtWidgets.QLabel(self.centralwidget)
        self.score.setGeometry(QtCore.QRect(60, 180, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.score.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.score.setFont(font)
        self.score.setAlignment(QtCore.Qt.AlignCenter)
        self.score.setObjectName("menu_highscore")

    def make_menu_title(self):
        self.menu_title = QtWidgets.QLabel(self.centralwidget)
        self.menu_title.setGeometry(QtCore.QRect(0, 130, 1280, 191))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.menu_title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.menu_title.setFont(font)
        self.menu_title.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_title.setObjectName("menu_title")

    def make_background(self):
        self.menu_background = QtWidgets.QLabel(self.centralwidget)
        self.menu_background.setEnabled(True)
        self.menu_background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.menu_background.setText("")
        self.menu_background.setPixmap(QtGui.QPixmap("images/stars_background.gif"))
        self.menu_background.setScaledContents(True)
        self.menu_background.setObjectName("menu_background")

    def make_info_label(self):
        self.menu_info = QtWidgets.QLabel(self.centralwidget)
        self.menu_info.setGeometry(QtCore.QRect(60, 280, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.menu_info.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menu_info.setFont(font)
        self.menu_info.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_info.setObjectName("menu_info")

    def make_coin_label(self):
        self.coin_label = QtWidgets.QLabel(self.centralwidget)
        self.coin_label.setGeometry(QtCore.QRect(60, 280, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.coin_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.coin_label.setFont(font)
        self.coin_label.setAlignment(QtCore.Qt.AlignCenter)
        self.coin_label.setObjectName("coin_label")

    def make_chest_label(self):
        self.chest_label = QtWidgets.QLabel(self.centralwidget)
        self.chest_label.setGeometry(QtCore.QRect(60, 280, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chest_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.chest_label.setFont(font)
        self.chest_label.setAlignment(QtCore.Qt.AlignCenter)
        self.chest_label.setObjectName("chest_label")
        self.chest_label.hide()

    def make_start_btn(self):
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_btn_config(self.play_btn)
        self.play_btn.setGeometry(QtCore.QRect(545, 400, 191, 71))
        self.play_btn.setObjectName("play_btn")
        self.play_btn.clicked.connect(self.start_btn_click)

    def start_btn_click(self):
        x = SoundThread("shotClick.wav")
        x.start()
        self.core.reload_main_game()

    def make_exit_btn(self):
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_btn_config(self.exit_btn)
        self.exit_btn.setGeometry(QtCore.QRect(545, 500, 191, 71))
        self.exit_btn.setObjectName("exit_btn")
        self.exit_btn.clicked.connect(self.exit_btn_click)

    def exit_btn_click(self):
        if self.chest_timer:
            self.chest_timer.stop()
        x = SoundThread("shotError.wav")
        x.start()
        sys.exit()

    def make_menu_btn(self):
        self.menu_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_btn_config(self.menu_btn)
        self.menu_btn.setGeometry(QtCore.QRect(545, 400, 191, 71))
        self.menu_btn.setObjectName("menu_btn")
        self.menu_btn.clicked.connect(self.menu_btn_click)

    def menu_btn_click(self):
        x = SoundThread("shotClick.wav")
        x.start()
        self.core.reload_main_menu()
        self.core.start_menu_music()

    def make_chest_btn(self):
        self.chest_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_btn_config(self.chest_btn)
        self.chest_btn.setGeometry(QtCore.QRect(545, 500, 191, 71))
        self.chest_btn.setObjectName("exit_btn")
        self.chest_btn.clicked.connect(self.open_chest)

    def open_chest(self):
        x = SoundThread("shotFanfar.wav")
        x.start()

        coins = Chest().open(Postac.score)
        self.coin_label.setText("Coins: " + str(JsonConnector.get_from_config("coins")))
        self.chest_label.setText("Award: " + str(coins) + " coins")

        self.start_chest_anim()

        self.chest_btn.setParent(None)
        self.chest_btn.deleteLater()
        self.chest_btn = None

    def make_chest_image(self):
        self.chest_image = QtWidgets.QLabel(self.centralwidget)
        self.chest_image.setGeometry(QtCore.QRect(0, 0, 400, 400))
        self.chest_image.setEnabled(True)
        self.chest_image.setText("")
        self.chest_image.setPixmap(QtGui.QPixmap("images/chest.gif"))
        self.chest_image.setScaledContents(True)
        self.chest_image.setObjectName("chest_image")

    def start_chest_anim(self):
        self.chest_movie = QtGui.QMovie("images/chest.gif", QByteArray(), self.chest_image)
        self.chest_movie.setSpeed(100)
        self.chest_movie.setCacheMode(QtGui.QMovie.CacheAll)
        self.chest_image.setMovie(self.chest_movie)
        self.chest_movie.start()

        self.chest_timer = QTimer()
        self.chest_timer.timeout.connect(lambda: self.stop_chest_anim(self.chest_timer, self.chest_movie))
        self.chest_timer.start(1000)

    def stop_chest_anim(self, timer, movie):
        movie.stop()
        timer.stop()

        self.chest_label.show()

        movie.jumpToFrame(movie.frameCount()-1)


    def get_btn_palette(self):
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        return palette

    def set_btn_config(self, btn_inst):
        palette = self.get_btn_palette()
        btn_inst.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        btn_inst.setFont(font)
        btn_inst.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        btn_inst.setMouseTracking(False)
        btn_inst.setFocusPolicy(QtCore.Qt.StrongFocus)
        btn_inst.setToolTip("")
        btn_inst.setAutoFillBackground(True)
        btn_inst.setCheckable(False)
        btn_inst.setAutoDefault(False)
        btn_inst.setDefault(False)
        btn_inst.setFlat(True)
